language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

matrix:
  fast_finish: true

branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

before_install:
- pip install pip --upgrade

install:
- pip install pytest future six
- pip install .

script: py.test -v -rsx
