language: python

python: 2.7

matrix:
  fast_finish: true

branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

before_install:
- pip install pip --upgrade

install:
- pip install .

script: pytest -v -rsx
