#+TITLE: The MetMask Project
#+OPTIONS: toc:nil num:nil skip:nil creator:nil author:nil
#+AUTHOR: henning
#+EMAIL: henning near psc point riken point jp

#+begin_html
    <center>
      <p>
        <font size="4" face="sans-serif">
          [ <a href="http://sourceforge.net/projects/metmask/">Project page</a> | <a href="http://sourceforge.net/projects/metmask/files">Download</a> | <a href="http://sourceforge.net/projects/metmask/forums">Forum</a>]
        </font>
      </p>
    </center>
#+end_html
* Webtool help
----------------------------------------------------------
#<<weak>>
** Weak identifiers
MetMask distinguishes between identifiers that are can be (or are at least somehow meant to) refer to a specific metabolite and identifiers that just label them. Real identifiers are called /strong/ and are used to refer to a specific metabolites or derivative. Other identifiers are called /weak/ and can be annotated to more than one distinctly different metabolites. 

Examples of strong indentifiers are synonyms like "Alanine", "L-Alanine" and the KEGG identifier "C00041" because they all (in metabolomics data) refer to the same structure; L-Alanine.

Examples of weak identifiers are synonyms like "G" or "sugar" or the mass formula C6H1206. 
#<<wild>>
** Wild cards
MetMask provides (very) basic support for using wild cards. A percentage sign (%) equals any number of any characters and an under-score (_) refers to any single character. See documentation of [[http://www.sqlite.org/lang_expr.html][SQLite operators]] for further details.
#<<table>>
** Table output
Provide output in a table. Each metabolite comes on single row in the table. Note for every identifier type (e.g. synonym) and metabolite (group of metabolites as MetMask understands it) there might be several single identifiers.
#<<graph>>
** Graph output
MetMask can generate a connection graph for the selected types of output identifiers and display them. Note that the graph might not be fully connected if not all identifiers types are chosen. Be warned that generating a graph with all identifier types may generate a very large graph. Grey edges are /weak/ identifiers, black are /strong/ identifiers. The edges have the source of evidence annotated to them and node names are the identifier preceded by the first two letters of the identifier type (e.g. synonym alanine becomes sy:alanine). For brevity all identifiers are truncated to the first 15 characters.

The figure is a PDF generated by [[http://www.bioconductor.org/packages/release/bioc/html/Rgraphviz.html][Rgraphviz]]. If you choose plain text output the generated  output can easily be imported to [[http:www.cytoscape.org][cytoscape]].  
#<<text>>
** Plain Text
Provide output in as plain text instead. For graph output this becomes a table like:
| from        | to          | source             | weak                      |
|-------------+-------------+--------------------+---------------------------|
| source node | target node | source of evidence | True for weak identifiers |

fields are tab-delimited.

For tables, the output is read like:
| identifier type 1 | identifier type 2 | ... |
|-------------------+-------------------+-----|
| id1  (pipe) id2   | id1 (pipe) id2    | ... |

where the identifier types are tab-separated but the individual identifiers are separated by the pipe (|) character.
